AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'availability-canary'
      Handler: availability-canary.lambda_handler
      Runtime: python3.8
      CodeUri: lambda_function.zip
      MemorySize: 128
      Timeout: 30
      Policies:
        - Statement:
            - Sid: SSMGetParamsByPath
              Effect: Allow
              Action:
                - ssm:GetParametersByPath
              Resource: 'arn:aws:ssm:us-east-1:476889715112:parameter/epic-shelter'
        - Statement:
            - Sid: SQSpushRecord
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: 'arn:aws:sqs:us-east-1:476889715112:DatabaseMessageQueue'
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SSM_PATH: '/epic-shelter'
          TZ: America/New_York
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunction}"
      RetentionInDays: 7
  ErrorsAlarm: # Alarm if 5 errors in a row ( 1 per min for 5 min )
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - arn:aws:sns:us-east-1:476889715112:unhealthyHost
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1 # this is the M in "M out of N data points to alarm"
      EvaluationPeriods: 5 # this is the N in "M out of N data points to alarm"
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60 # seconds between data points
      Statistic: Sum
      Threshold: '1'
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: availability-canary
  InvocationsAlarm: # Alarm if we're not getting any invocations
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - arn:aws:sns:us-east-1:476889715112:unhealthyHost
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 5 # number of failed data points to trigger
      MetricName: Invocations
      Namespace: AWS/Lambda
      Period: 60 # seconds
      Statistic: Sum
      Threshold: '1'
      TreatMissingData: breaching
      Dimensions:
        - Name: FunctionName
          Value: availability-canary